src/Entity/ForumBan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * Represents a ban or unban action that applies to a user and a forum.
 *
 * @ORM\Entity(repositoryClass="App\Repository\ForumBanRepository")
 * @ORM\Table(name="forum_bans")
 */
class ForumBan {
    /**
     * @ORM\Column(type="uuid")
     * @ORM\Id()
     *
     * @var Uuid
     */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="Forum", inversedBy="bans")
     *
     * @var Forum
     */
    private $forum;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $reason;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $banned;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $bannedBy;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $timestamp;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     *
     * @var \DateTime|null
     */
    private $expiresAt;

    public function __construct(
        Forum $forum,
        User $user,
        string $reason,
        bool $banned,
        User $bannedBy,
        \DateTime $expiresAt = null,
        \DateTime $timestamp = null
    ) {
        if (!$banned && $expiresAt) {
            throw new \DomainException('Unbans cannot have expiry times');
        }

        $this->id = Uuid::uuid4();
        $this->forum = $forum;
        $this->user = $user;
        $this->reason = $reason;
        $this->banned = $banned;
        $this->bannedBy = $bannedBy;
        $this->expiresAt = $expiresAt;

        // since the last ban takes precedence, and because timestamps are used
        // for sorting, we'll use microseconds to hopefully avoid collisions
        $this->timestamp = $timestamp ?:
            \DateTime::createFromFormat('U.u', microtime(true));
    }

    public function getId(): Uuid {
        return $this->id;
    }

    public function getForum(): Forum {
        return $this->forum;
    }

    public function getUser(): User {
        return $this->user;
    }

    public function getReason(): string {
        return $this->reason;
    }

    public function isBan(): bool {
        return $this->banned;
    }

    public function getBannedBy(): User {
        return $this->bannedBy;
    }

    public function getTimestamp(): \DateTime {
        return $this->timestamp;
    }

    public function getExpiryTime(): ?\DateTime {
        return $this->expiresAt;
    }

    public function isExpired() {
        if ($this->expiresAt === null) {
            return false;
        }

        return $this->expiresAt < \DateTime::createFromFormat('U.u', microtime(true));
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Selectable;
use Doctrine\ORM\Mapping as ORM;
use Pagerfanta\Adapter\DoctrineCollectionAdapter;
use Pagerfanta\Adapter\DoctrineSelectableAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="users", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="users_username_idx", columns={"username"}),
 *     @ORM\UniqueConstraint(name="users_normalized_username_idx", columns={"normalized_username"}),
 * })
 */
class User implements UserInterface, EquatableInterface {
    const FRONT_DEFAULT = 'default';
    const FRONT_FEATURED = 'featured';
    const FRONT_SUBSCRIBED = 'subscribed';
    const FRONT_ALL = 'all';
    const FRONT_MODERATED = 'moderated';

    const FRONT_PAGE_CHOICES = [
        self::FRONT_DEFAULT,
        self::FRONT_FEATURED,
        self::FRONT_SUBSCRIBED,
        self::FRONT_ALL,
        self::FRONT_MODERATED,
    ];

    /**
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Id()
     *
     * @var int|null
     */
    private $id;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string
     */
    private $username;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string
     */
    private $normalizedUsername;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $password;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string|null
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string|null
     */
    private $normalizedEmail;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $created;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     *
     * @var \DateTime|null
     */
    private $lastSeen;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     *
     * @var bool
     */
    private $admin = false;

    /**
     * @ORM\OneToMany(targetEntity="Moderator", mappedBy="user")
     *
     * @var Moderator[]|Collection
     */
    private $moderatorTokens;

    /**
     * @ORM\OneToMany(targetEntity="Submission", mappedBy="user", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"id": "DESC"})
     *
     * @var Submission[]|Collection|Selectable
     */
    private $submissions;

    /**
     * @ORM\OneToMany(targetEntity="SubmissionVote", mappedBy="user", fetch="EXTRA_LAZY")
     *
     * @var SubmissionVote[]|Collection
     */
    private $submissionVotes;

    /**
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="user", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"id": "DESC"})
     *
     * @var Comment[]|Collection|Selectable
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="CommentVote", mappedBy="user", fetch="EXTRA_LAZY")
     *
     * @var CommentVote[]|Collection
     */
    private $commentVotes;

    /**
     * @ORM\OneToMany(targetEntity="UserBan", mappedBy="user")
     *
     * @var UserBan[]|Collection|Selectable
     */
    private $bans;

    /**
     * @ORM\OneToMany(targetEntity="IpBan", mappedBy="user")
     *
     * @var IpBan[]|Collection|Selectable
     */
    private $ipBans;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $locale = 'en';

    /**
     * @ORM\OneToMany(targetEntity="Notification", mappedBy="user", fetch="EXTRA_LAZY", cascade={"persist"})
     *
     * @var Notification[]|Collection|Selectable
     */
    private $notifications;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $nightMode = false;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     *
     * @var bool
     */
    private $showCustomStylesheets = true;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     *
     * @var bool
     */
    private $trusted = false;

    /**
     * @ORM\ManyToOne(targetEntity="Theme")
     *
     * @var Theme|null
     */
    private $preferredTheme;

    /**
     * @ORM\OneToMany(targetEntity="UserBlock", mappedBy="blocker")
     * @ORM\OrderBy({"timestamp": "DESC"})
     *
     * @var UserBlock[]|Collection|Selectable
     */
    private $blocks;

    /**
     * @ORM\Column(type="text", options={"default": "default"})
     *
     * @var string
     */
    private $frontPage = self::FRONT_DEFAULT;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     *
     * @var bool
     */
    private $openExternalLinksInNewTab = false;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string|null
     */
    private $biography;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     *
     * @var bool
     */
    private $autoFetchSubmissionTitles = true;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     *
     * @var bool
     */
    private $enablePostPreviews = true;

    public function __construct(string $username, string $password, \DateTime $created = null) {
        $this->setUsername($username);
        $this->password = $password;
        $this->created = $created ?: new \DateTime('@'.time());
        $this->notifications = new ArrayCollection();
        $this->submissions = new ArrayCollection();
        $this->submissionVotes = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->commentVotes = new ArrayCollection();
        $this->bans = new ArrayCollection();
        $this->ipBans = new ArrayCollection();
        $this->blocks = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getUsername(): string {
        return $this->username;
    }

    public function setUsername(string $username) {
        $this->username = $username;
        $this->normalizedUsername = self::normalizeUsername($username);
    }

    public function getNormalizedUsername(): string {
        return $this->normalizedUsername;
    }

    public function getPassword(): string {
        return $this->password;
    }

    public function setPassword(string $password) {
        $this->password = $password;
    }

    public function getEmail(): ?string {
        return $this->email;
    }

    public function setEmail(?string $email) {
        $this->email = $email;
        $this->normalizedEmail = $email ? self::normalizeEmail($email) : null;
    }

    /**
     * Retrieve the normalized email address.
     *
     * Sending email to the normalized address is evil. Use this for lookup,
     * but *always* send to the regular, canon address.
     *
     * @return string|null
     */
    public function getNormalizedEmail(): ?string {
        return $this->normalizedEmail;
    }

    public function getCreated(): \DateTime {
        return $this->created;
    }

    public function getLastSeen(): ?\DateTime {
        return $this->lastSeen;
    }

    public function setLastSeen(?\DateTime $lastSeen) {
        $this->lastSeen = $lastSeen;
    }

    public function isAdmin(): bool {
        return $this->admin;
    }

    public function setAdmin(bool $admin) {
        $this->admin = $admin;
    }

    /**
     * @return Collection|Moderator[]
     */
    public function getModeratorTokens(): Collection {
        return $this->moderatorTokens;
    }

    /**
     * {@inheritdoc}
     */
    public function getRoles() {
        $roles = ['ROLE_USER'];

        if ($this->admin) {
            $roles[] = 'ROLE_ADMIN';
        }

        if ($this->trusted) {
            $roles[] = 'ROLE_TRUSTED_USER';
        }

        return $roles;
    }

    /**
     * {@inheritdoc}
     */
    public function getSalt() {
        // Salt is not needed when bcrypt is used, as the password hash contains
        // the salt.
        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function eraseCredentials() {
    }

    /**
     * @return Collection|Selectable|Submission[]
     */
    public function getSubmissions(): Collection {
        return $this->submissions;
    }

    /**
     * @param int $page
     * @param int $maxPerPage
     *
     * @return Pagerfanta|Comment[]
     */
    public function getPaginatedSubmissions(int $page, int $maxPerPage = 25): Pagerfanta {
        $submissions = new Pagerfanta(new DoctrineCollectionAdapter($this->submissions));
        $submissions->setMaxPerPage($maxPerPage);
        $submissions->setCurrentPage($page);

        return $submissions;
    }

    public function getSubmissionVotes(): Collection {
        return $this->submissionVotes;
    }

    /**
     * @return Collection|Selectable|Comment[]
     */
    public function getComments(): Collection {
        return $this->comments;
    }

    /**
     * @param int $page
     * @param int $maxPerPage
     *
     * @return Pagerfanta|Comment[]
     */
    public function getPaginatedComments(int $page, int $maxPerPage = 25): Pagerfanta {
        $comments = new Pagerfanta(new DoctrineCollectionAdapter($this->comments));
        $comments->setMaxPerPage($maxPerPage);
        $comments->setCurrentPage($page);

        return $comments;
    }

    public function getCommentVotes(): Collection {
        return $this->commentVotes;
    }

    /**
     * @return UserBan[]|Collection
     */
    public function getBans(): Collection {
        return $this->bans;
    }

    public function addBan(UserBan $ban) {
        if (!$this->bans->contains($ban)) {
            $this->bans->add($ban);
        }
    }

    public function isBanned(): bool {
        $criteria = Criteria::create()

src/Form/UserType.php
<?php

namespace App\Form;

use App\Form\EventListener\PasswordEncodingSubscriber;
use App\Form\Model\UserData;
use App\Form\Type\HoneypotType;
use Gregwar\CaptchaBundle\Type\CaptchaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

final class UserType extends AbstractType {
    /**
     * @var UserPasswordEncoderInterface
     */
    private $encoder;

    /**
     * @var AuthorizationCheckerInterface
     */
    private $authorizationChecker;

    /**
     * @param UserPasswordEncoderInterface  $encoder
     * @param AuthorizationCheckerInterface $authorizationChecker
     */
    public function __construct(
        UserPasswordEncoderInterface $encoder,
        AuthorizationCheckerInterface $authorizationChecker
    ) {
        $this->encoder = $encoder;
        $this->authorizationChecker = $authorizationChecker;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        if ($options['honeypot']) {
            $builder->add('phone', HoneypotType::class);
        }

        $editing = $builder->getData() && $builder->getData()->getEntityId();

        $builder
            ->add('username', TextType::class)
            ->add('password', RepeatedType::class, [
                'property_path' => 'plainPassword',
                'required' => !$editing,
                'first_options' => ['label' => $editing ? 'user_form.new_password' : 'user_form.password'],
                'second_options' => ['label' => $editing ? 'user_form.repeat_new_password' : 'user_form.repeat_password'],
                'type' => PasswordType::class,
            ])
            ->add('email', EmailType::class, [
                'required' => false,
            ]);

        if (!$editing) {
            $builder->add('verification', CaptchaType::class, [
                'as_url' => true,
                'reload' => true,
            ]);
        }

        $builder->add('submit', SubmitType::class, [
            'label' => 'user_form.'.($editing ? 'save' : 'register'),
        ]);

        $builder->addEventSubscriber(new PasswordEncodingSubscriber($this->encoder));
    }

    public function finishView(FormView $view, FormInterface $form, array $options) {
        if ($form->getData() && $form->getData()->getEntityId()) {
            // don't auto-complete the password fields when editing the user
            $view['password']['first']->vars['attr']['autocomplete'] = 'new-password';
            $view['password']['second']->vars['attr']['autocomplete'] = 'new-password';
        }
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => UserData::class,
            'honeypot' => true,
            'label_format' => 'user_form.%name%',
            'validation_groups' => function (FormInterface $form) {
                if ($form->getData()->getEntityId() !== null) {
                    $groups[] = 'edit';
                } else {
                    $groups[] = 'registration';
                }

                return $groups;
            },
        ]);

        $resolver->setAllowedTypes('honeypot', ['bool']);
    }
}

templates/user/_macros.html.twig
{##
 # - submitter (bool): If comment author is the submission author
 # - flag (int|string): one of App\Entity\UserFlags constants, or 'admin'/'moderator'
 # - class (string): Additional classes
 #}
{%- macro user_link(user, options) -%}
  {%- from _self import _class_by_flag -%}
  <a href="{{ path('user', {username: user.username}) }}"
     class="{{ (options.submitter ?? false) ? 'submitter' }} {{ _class_by_flag(options.flag ?? 0) }} {{ options.class ?? '' }}">
    {{- (options.prefix ?? false) ? '/u/' -}}
    {{- user.username -}}
  </a>
  {%- if options.flag ?? 0 is same as(0) -%}
  {% elseif options.flag == constant('App\\Entity\\UserFlags::FLAG_ADMIN') or options.flag == 'admin' %}
    <small class="user-flag user-flag-admin">{{ 'user_flag.admin'|trans }}</small>
  {% elseif options.flag == constant('App\\Entity\\UserFlags::FLAG_MODERATOR') or options.flag == 'moderator' %}
    <small class="user-flag user-flag-moderator">{{ 'user_flag.moderator'|trans }}</small>
  {%- endif -%}
{%- endmacro -%}

{%- macro _class_by_flag(flag) -%}
  {%- if flag is same as(0) -%}
    {#- early exit -#}
  {%- elseif flag == constant('App\\Entity\\UserFlags::FLAG_ADMIN') or flag == 'admin' -%}
    flag-admin
  {%- elseif flag == constant('App\\Entity\\UserFlags::FLAG_MODERATOR') or flag == 'moderator' -%}
    flag-moderator
  {%- endif -%}
{%- endmacro -%}

templates/user/_nav.html.twig
<nav class="tabs user-nav">
  <ul class="tabs__bar">
    {% for tab in [
      { path: 'user', label: 'label.overview' },
      { path: 'user_submissions', label: 'user.submissions' },
      { path: 'user_comments', label: 'user.comments' },
    ] %}
      <li class="tabs__tab {{ tab.path == current ? 'tabs__tab--active' }}">
        <a href="{{ path(tab.path, {username: user.username}) }}"
           class="tabs__link {{ tab.path == current ? 'tabs__link--active' }}">
          {{- tab.label|trans -}}
        </a>
      </li>
    {% endfor %}
  </ul>
</nav>

templates/user/base.html.twig
{% extends 'base.html.twig' %}

{% from _self import timestamp %}

{% block sidebar %}
  <section class="sidebar__section user-bio">
    <h1 class="sidebar__title user-bio__title">
      <a href="{{ path('user', {username: user.username}) }}" class="user-bio__user-link">{{ user.username }}</a>
    </h1>

    <p class="user-bio__registered">{{ 'user.registered'|trans({
      '%timestamp%': timestamp(user.created)
    })|raw }}</p>

    {% if user.biography is not empty %}
      <div class="user-bio__biography">{{ user.biography|cached_markdown(markdown_context())|raw }}</div>
    {% endif %}
  </section>

  {% set toolbox_items = [] %}

  {% if is_granted('ROLE_USER') and user is not same as(app.user) %}
    {% if is_granted('message', user)  %}
      {% set item %}
        <li><a href="{{ path('compose_message', {username: user.username}) }}">{{ 'user.message'|trans }}</a></li>
      {% endset %}
      {% set toolbox_items = toolbox_items|merge([item]) %}
    {% endif %}

    {% if not app.user.isBlocking(user) %}
      {% set item %}
        <li><a href="{{ path('block_user', {username: user.username}) }}">{{ 'nav.block_user'|trans }}</a></li>
      {% endset %}
      {% set toolbox_items = toolbox_items|merge([item]) %}
    {% endif %}

    {% if is_granted('ROLE_ADMIN') %}
      {% set item %}
        {% if not user.banned %}
          <li><a href="{{ path('ban_user', {username: user.username}) }}">{{ 'action.ban'|trans }}</a></li>
        {% else %}
          <li><a href="{{ path('unban_user', {username: user.username}) }}">{{ 'action.unban'|trans }}</a></li>
        {% endif %}
      {% endset %}
      {% set toolbox_items = toolbox_items|merge([item]) %}

      {% set item %}
        <li><a href="{{ path('user_forum_bans', {username: user.username}) }}">{{ 'nav.forum_bans'|trans }}</a></li>
      {% endset %}
      {% set toolbox_items = toolbox_items|merge([item]) %}
    {% endif %}
  {% endif %}

  {% if user is same as(app.user) %}
    {% set item %}
      <li><a href="{{ path('edit_biography', {username: user.username}) }}">{{ 'nav.edit_biography'|trans }}</a></li>
    {% endset %}
    {% set toolbox_items = toolbox_items|merge([item]) %}
  {% endif %}

  {% if toolbox_items %}
    <section class="sidebar__section sidebar__section--user-toolbox">
      <h1 class="sidebar__title">{{ 'label.toolbox'|trans }}</h1>
      <ul>
        {% for item in toolbox_items %}
          {{ item }}
        {% endfor %}
      </ul>
    </section>
  {% endif %}

  {% if is_granted('ROLE_ADMIN') %}
    <section class="sidebar__section sidebar__section--user-roles">
      <h1 class="sidebar__title">{{ 'heading.user_roles'|trans }}</h1>
      <form action="{{ path('mark_user_trusted', {id: user.id, trusted: not user.trusted ? 1 : 0}) }}" method="post" class="form">
        <input type="hidden" name="token" value="{{ csrf_token('mark_trusted') }}">
        <div class="form__row">
          <button class="button">{{ (not user.trusted ? 'action.mark_as_trusted' : 'action.mark_as_untrusted')|trans }}</button>
        </div>
      </form>
    </section>
  {% endif %}

  {% if user.moderatorTokens|length > 0 %}
    <section class="sidebar__section sidebar__section--user-moderator-info">
      <h1 class="sidebar__title">{{ 'user.moderates'|trans({'%username%': user.username}) }}</h1>
      <ul>
        {% for token in user.moderatorTokens %}
          <li><a href="{{ path('forum', {forum_name: token.forum.name}) }}">{{ token.forum.name }}</a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
{% endblock %}

{%- macro timestamp(timestamp) -%}
  {%- set date = timestamp|localizeddate('long', 'short') -%}
  <time datetime="{{ timestamp|date('c') }}" class="relative-time" title="{{ date }}">
    {{- 'time.on_timestamp'|trans({'%timestamp%': date}) -}}
  </time>
{%- endmacro -%}

templates/user/block.html.twig
{% extends 'base.html.twig' %}
{% from 'user/_macros.html.twig' import user_link %}

{% block page_classes 'user-block-page' %}
{% block title 'title.blocking_user'|trans({'%user%': '/u/'~blockee.username}) %}

{% block body %}
  <h1 class="page-heading">
    {{ 'title.blocking_user'|trans({
      '%user%': user_link(blockee, {prefix: true}),
    })|raw }}
  </h1>

  <div class="alert alert--notice">
    <p>{{ 'help.block_users'|trans }}</p>
  </div>

  {{ form(form) }}
{% endblock %}

templates/user/block_list.html.twig
{% extends 'base.html.twig' %}

{% block page_classes 'user-block-list-page' %}
{% block title 'title.block_list'|trans %}

{% from 'user/_macros.html.twig' import user_link %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  <div class="alert alert--notice">
    <p>{{ 'help.block_users'|trans }}</p>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>{{ 'label.username'|trans }}</th>
        <th>{{ 'label.blocked'|trans }}</th>
        <th>{{ 'label.comment'|trans }}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for block in blocks %}
        <tr>
          <td>{{ user_link(block.blocked) }}</td>
          <td>
            {% with {date: block.timestamp|localizeddate('long', 'short')} %}
            <time datetime="{{ block.timestamp|date('c') }}" title="{{ date }}" class="relative-time">
              {{- date -}}
            </time>
            {% endwith %}
          </td>
          <td>{{ block.comment }}</td>
          <td>
            <form action="{{ path('unblock_user', {id: block.id}) }}" method="post">
              <input type="hidden" name="token" value="{{ csrf_token('unblock') }}">
              <button class="button button--inline">{{ 'action.unblock'|trans }}</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'edit_user.title'|trans({'%username%': user.username}) }}{% endblock %}

{% block page_classes %}edit-user-page{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {% include 'user/_form.html.twig' %}
{% endblock %}

templates/user/forum_bans.html.twig
{% extends 'base.html.twig' %}

{% block title 'title.user_forum_bans'|trans({'%user%': user.username}) %}

{% block head %}
  {{ parent() }}

  {{ include('_includes/meta_pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock %}

{% block body %}
  {% from 'user/_macros.html.twig' import user_link %}

  <h1 class="page-heading">
    {{ 'title.user_forum_bans'|trans({'%user%': user_link(user, {prefix: true})})|raw }}
  </h1>

  {% if bans|length > 0 %}
    <table class="table">
      <thead>
        <tr>
          <th>{{ 'label.forum'|trans }}</th>
          <th>{{ 'label.banned_by'|trans }}</th>
          <th>{{ 'label.banned'|trans }}</th>
          <th>{{ 'label.expires'|trans }}</th>
          <th>{{ 'label.reason'|trans }}</th>
        </tr>
      </thead>
      <tbody>
        {% for ban in bans %}
          <tr>
            <td><a href="{{ path('forum', {forum_name: ban.forum.name}) }}">/f/{{ ban.forum.name }}</a></td>
            <td>{{ user_link(ban.bannedBy) }}</td>
            <td>
              {% with { date: ban.timestamp|localizeddate('long', 'short') } %}
                <time datetime="{{ ban.timestamp|date('c') }}" class="relative-time" title="{{ date }}">
                  {{- date -}}
                </time>
              {% endwith %}
            </td>
            <td>
              {% if ban.expiryTime %}
                {% set date = ban.expiryTime|localizeddate('long', 'short') %}
                <time datetime="{{ ban.expiryTime|date('c') }}" class="relative-time" title="{{ date }}">
                  {{- date -}}
                </time>
              {% else %}
                <small>{{ 'label.never'|trans }}</small>
              {% endif %}
            </td>
            <td>{{ ban.reason }}</td>
            <td>
              <a href="{{ path('unban_user', {username: ban.user.username}) }}" class="button button--inline">
                {{ 'action.unban'|trans }}
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="no-entries">
      <small class="dimmed">{{ 'flash.no_entries_to_display'|trans }}</small>
    </p>
  {% endif %}

  {{ include('_includes/pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock %}

templates/user/registration.html.twig
{% extends 'base.html.twig' %}

{% block page_classes %}registration-page{% endblock %}
{% block title 'title.sign_up'|trans %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {% include 'user/_form.html.twig' %}
{% endblock %}